apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: movie-writer
  name: movie-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-writer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: movie-writer
    spec:
      containers:
      - image: 218005993626.dkr.ecr.us-east-1.amazonaws.com/movie-writer:latest
        name: movie-writer
        resources: {}
        ports:
          - containerPort: 9090
        env:
          - name: MONGO_CONNECTION_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-creds
                key: connectionString
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: accessKey
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: secretKey
      imagePullSecrets:
        - name: docker-creds
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: movie-writer
  name: movie-writer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
  - name: "9090-9090"
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: movie-writer
  type: LoadBalancer
status:
  loadBalancer: {}
