apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-admin-secret
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: admin-scram
    - name: moviesAppUser
      db: admin
      passwordSecretRef:
        name: mongodb-movie-user-secret
      roles:
        - name: readWrite
          db: movies
      scramCredentialsSecretName: movie-user-scram
  statefulSet:
    spec:
       volumeClaimTemplate: 
          - metadata:
              name: "mongo-pvc"
            spec:
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: 2G
              selector:
                matchLabels:
                  name: "mongo-pv"
              storageClassName: "efs-sc"  

  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib